# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "eurolinux-vagrant/centos-stream-9"
  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"
  (1..3).each do |i|
    config.vm.define "centosvm#{i}" do |vm_config|
	  vm_config.vm.hostname = "centosvm#{i}"
	  vm_config.vm.network "private_network", ip: "192.168.50.1#{i}"
	  vm_config.vm.provider "virtualbox" do |vb|
	    vb.name = "centosvm#{i}"
        vb.memory = "1024"
		vb.cpus = 1
      end
    end
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end